language: python

python: "2.7"

dist: trusty

git:
  depth: 3

install:
  - pip install pygame numpy

script:
  - ./double-pendulum -h

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
